name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build-lint-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            checkTarget: true
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Check format
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --logger "console;verbosity=detailed"
