name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build-lint-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            checkTarget: true
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Check format
        if: ${{ matrix.checkTarget }}
        run: dotnet format --verify-no-changes

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test --logger "console;verbosity=detailed"

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-lint-test
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Build docs
        run: |
          dotnet tool update -g docfx
          docfx src/NexusRpc/docs/docfx.json --warningsAsErrors

      - name: Upload docs to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: src/NexusRpc/docs/_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
